[2024-10-06T16:08:37.948+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-06T16:08:38.159+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.choose_source manual__2024-10-06T23:07:58+07:00 [queued]>
[2024-10-06T16:08:38.268+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.choose_source manual__2024-10-06T23:07:58+07:00 [queued]>
[2024-10-06T16:08:38.274+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-06T16:08:38.357+0000] {taskinstance.py:2888} INFO - Executing <Task(BranchPythonOperator): choose_source> on 2024-10-06 16:07:58+00:00
[2024-10-06T16:08:38.425+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=123) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-06T16:08:38.463+0000] {standard_task_runner.py:72} INFO - Started process 136 to run task
[2024-10-06T16:08:38.558+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'choose_source', 'manual__2024-10-06T23:07:58+07:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpk7dh9x6w']
[2024-10-06T16:08:38.626+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask choose_source
[2024-10-06T16:08:41.471+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.choose_source manual__2024-10-06T23:07:58+07:00 [running]> on host 8dc237c78455
[2024-10-06T16:08:42.124+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='choose_source' AIRFLOW_CTX_EXECUTION_DATE='2024-10-06T16:07:58+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-06T23:07:58+07:00'
[2024-10-06T16:08:42.144+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-06T16:08:42.253+0000] {baseoperator.py:405} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-10-06T16:08:42.268+0000] {logging_mixin.py:190} INFO - Selected source type: csv
[2024-10-06T16:08:42.270+0000] {python.py:240} INFO - Done. Returned value was: extract_csv
[2024-10-06T16:08:42.271+0000] {branch.py:38} INFO - Branch into extract_csv
[2024-10-06T16:08:42.272+0000] {skipmixin.py:230} INFO - Following branch ('extract_csv',)
[2024-10-06T16:08:42.459+0000] {skipmixin.py:278} INFO - Skipping tasks [('extract_json', -1)]
[2024-10-06T16:08:42.901+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-06T16:08:42.904+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=choose_source, run_id=manual__2024-10-06T23:07:58+07:00, execution_date=20241006T160758, start_date=20241006T160838, end_date=20241006T160842
[2024-10-06T16:08:43.071+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-06T16:08:44.526+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-10-06T16:08:44.601+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-06T16:08:44.625+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
