[2024-10-06T16:58:05.425+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-06T16:58:05.493+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.choose_source manual__2024-10-06T23:57:49+07:00 [queued]>
[2024-10-06T16:58:05.526+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.choose_source manual__2024-10-06T23:57:49+07:00 [queued]>
[2024-10-06T16:58:05.527+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-06T16:58:05.602+0000] {taskinstance.py:2888} INFO - Executing <Task(BranchPythonOperator): choose_source> on 2024-10-06 16:57:49+00:00
[2024-10-06T16:58:05.675+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=192) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-06T16:58:05.684+0000] {standard_task_runner.py:72} INFO - Started process 194 to run task
[2024-10-06T16:58:05.682+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'choose_source', 'manual__2024-10-06T23:57:49+07:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpzz27uh9h']
[2024-10-06T16:58:05.709+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask choose_source
[2024-10-06T16:58:06.080+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.choose_source manual__2024-10-06T23:57:49+07:00 [running]> on host 6f8fa0a60589
[2024-10-06T16:58:06.744+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='choose_source' AIRFLOW_CTX_EXECUTION_DATE='2024-10-06T16:57:49+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-06T23:57:49+07:00'
[2024-10-06T16:58:06.748+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-06T16:58:06.865+0000] {baseoperator.py:405} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-10-06T16:58:06.867+0000] {logging_mixin.py:190} INFO - Selected source type: csv
[2024-10-06T16:58:06.868+0000] {python.py:240} INFO - Done. Returned value was: extract_csv
[2024-10-06T16:58:06.869+0000] {branch.py:38} INFO - Branch into extract_csv
[2024-10-06T16:58:06.885+0000] {skipmixin.py:230} INFO - Following branch ('extract_csv',)
[2024-10-06T16:58:06.937+0000] {skipmixin.py:278} INFO - Skipping tasks [('extract_json', -1)]
[2024-10-06T16:58:07.430+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-06T16:58:07.432+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=choose_source, run_id=manual__2024-10-06T23:57:49+07:00, execution_date=20241006T165749, start_date=20241006T165805, end_date=20241006T165807
[2024-10-06T16:58:07.734+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-06T16:58:08.047+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-06T16:58:08.121+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
