[2024-10-06T19:24:34.051+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-06T19:24:34.157+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.choose_source manual__2024-10-07T02:20:39+07:00 [queued]>
[2024-10-06T19:24:34.256+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.choose_source manual__2024-10-07T02:20:39+07:00 [queued]>
[2024-10-06T19:24:34.264+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-06T19:24:34.493+0000] {taskinstance.py:2888} INFO - Executing <Task(BranchPythonOperator): choose_source> on 2024-10-06 19:20:39+00:00
[2024-10-06T19:24:34.583+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=442) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-06T19:24:34.615+0000] {standard_task_runner.py:72} INFO - Started process 444 to run task
[2024-10-06T19:24:34.639+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'choose_source', 'manual__2024-10-07T02:20:39+07:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp2gspurb_']
[2024-10-06T19:24:34.675+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask choose_source
[2024-10-06T19:24:35.528+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.choose_source manual__2024-10-07T02:20:39+07:00 [running]> on host c9ff1ae97c7a
[2024-10-06T19:24:36.207+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='choose_source' AIRFLOW_CTX_EXECUTION_DATE='2024-10-06T19:20:39+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-07T02:20:39+07:00'
[2024-10-06T19:24:36.216+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-06T19:24:36.320+0000] {baseoperator.py:405} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-10-06T19:24:36.331+0000] {logging_mixin.py:190} INFO - Selected source type: json
[2024-10-06T19:24:36.333+0000] {python.py:240} INFO - Done. Returned value was: extract_json
[2024-10-06T19:24:36.334+0000] {branch.py:38} INFO - Branch into extract_json
[2024-10-06T19:24:36.336+0000] {skipmixin.py:230} INFO - Following branch ('extract_json',)
[2024-10-06T19:24:36.378+0000] {skipmixin.py:278} INFO - Skipping tasks [('extract_csv', -1)]
[2024-10-06T19:24:36.511+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-06T19:24:36.518+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=choose_source, run_id=manual__2024-10-07T02:20:39+07:00, execution_date=20241006T192039, start_date=20241006T192434, end_date=20241006T192436
[2024-10-06T19:24:36.635+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-06T19:24:36.752+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-06T19:24:36.756+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
